# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messages/get_user_confirmation.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(320, 240)
        Dialog.setMinimumSize(QtCore.QSize(300, 240))
        Dialog.setMaximumSize(QtCore.QSize(650, 600))
        Dialog.setModal(True)
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_3.setHorizontalSpacing(2)
        self.gridLayout_3.setVerticalSpacing(4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_tile = QtWidgets.QFrame(Dialog)
        self.frame_tile.setMinimumSize(QtCore.QSize(0, 52))
        self.frame_tile.setMaximumSize(QtCore.QSize(650, 52))
        self.frame_tile.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame_tile.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_tile.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tile.setObjectName("frame_tile")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_tile)
        self.gridLayout.setContentsMargins(2, 2, 2, 0)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_rightButton = QtWidgets.QPushButton(self.frame_tile)
        self.pushButton_rightButton.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_rightButton.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_rightButton.setFont(font)
        self.pushButton_rightButton.setStyleSheet("")
        self.pushButton_rightButton.setAutoDefault(True)
        self.pushButton_rightButton.setDefault(False)
        self.pushButton_rightButton.setFlat(False)
        self.pushButton_rightButton.setObjectName("pushButton_rightButton")
        self.gridLayout.addWidget(self.pushButton_rightButton, 0, 3, 1, 1)
        self.pushButton_leftButton = QtWidgets.QPushButton(self.frame_tile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_leftButton.sizePolicy().hasHeightForWidth())
        self.pushButton_leftButton.setSizePolicy(sizePolicy)
        self.pushButton_leftButton.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_leftButton.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_leftButton.setFont(font)
        self.pushButton_leftButton.setStyleSheet("")
        self.pushButton_leftButton.setAutoDefault(False)
        self.pushButton_leftButton.setDefault(False)
        self.pushButton_leftButton.setFlat(False)
        self.pushButton_leftButton.setObjectName("pushButton_leftButton")
        self.gridLayout.addWidget(self.pushButton_leftButton, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_tile, 2, 0, 1, 1)
        self.label_message = QtWidgets.QLabel(Dialog)
        self.label_message.setMinimumSize(QtCore.QSize(0, 0))
        self.label_message.setMaximumSize(QtCore.QSize(650, 500))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_message.setFont(font)
        self.label_message.setFrameShape(QtWidgets.QFrame.Box)
        self.label_message.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_message.setLineWidth(1)
        self.label_message.setTextFormat(QtCore.Qt.AutoText)
        self.label_message.setAlignment(QtCore.Qt.AlignCenter)
        self.label_message.setObjectName("label_message")
        self.gridLayout_3.addWidget(self.label_message, 1, 0, 1, 1)
        self.label_title = QtWidgets.QLabel(Dialog)
        self.label_title.setMinimumSize(QtCore.QSize(0, 42))
        self.label_title.setMaximumSize(QtCore.QSize(650, 42))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("")
        self.label_title.setFrameShape(QtWidgets.QFrame.Box)
        self.label_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_title.setLineWidth(1)
        self.label_title.setTextFormat(QtCore.Qt.AutoText)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.gridLayout_3.addWidget(self.label_title, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Message"))
        self.pushButton_rightButton.setText(_translate("Dialog", "Right button"))
        self.pushButton_leftButton.setText(_translate("Dialog", "Left button"))
        self.label_message.setText(_translate("Dialog", "< message >"))
        self.label_title.setText(_translate("Dialog", "Title"))


class GetUserConfirmation_UI(QtWidgets.QDialog, Ui_Dialog):
    """
    Component Hierarchy:
    - Dialog: QDialog
        - (Layout): QGridLayout
                - frame_tile: QFrame
                    - (Layout): QGridLayout
                            - pushButton_rightButton: QPushButton
                            - pushButton_leftButton: QPushButton
                - label_message: QLabel
                - label_title: QLabel
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setupUi(self)
