# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messages/print_message.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 240)
        Dialog.setMinimumSize(QtCore.QSize(300, 240))
        Dialog.setMaximumSize(QtCore.QSize(650, 600))
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_button = QtWidgets.QFrame(Dialog)
        self.frame_button.setMinimumSize(QtCore.QSize(0, 48))
        self.frame_button.setMaximumSize(QtCore.QSize(650, 48))
        self.frame_button.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button.setObjectName("frame_button")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_button)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_close = QtWidgets.QPushButton(self.frame_button)
        self.pushButton_close.setMinimumSize(QtCore.QSize(80, 28))
        self.pushButton_close.setMaximumSize(QtCore.QSize(80, 28))
        self.pushButton_close.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_close.setFont(font)
        self.pushButton_close.setStyleSheet("QPushButton{border-radius: 6px; border-color: rgb(150, 150, 150); border-style: ridge; border-width: 2px; color: rgb(0, 0, 0); background-color: rgb(240, 240, 240)}\n"
"QPushButton:hover{border-radius: 6px; border-color: rgb(0, 170, 255); border-style: ridge; border-width: 2px; color: rgb(0, 0, 0); background-color: rgba(174, 213, 255, 100)}\n"
"QPushButton:pressed{border-radius: 6px; border-color: rgb(0, 170, 255); border-style: ridge; border-width: 2px; color: rgb(0, 0, 0); background-color: rgb(174, 213, 255)}\n"
"QPushButton:disabled{border-radius: 6px; border-color: rgb(150, 150, 150); border-style: ridge; border-width: 0px; color: rgb(150,150, 150); background-color: rgb(220, 220, 220)}")
        self.pushButton_close.setDefault(False)
        self.pushButton_close.setFlat(False)
        self.pushButton_close.setObjectName("pushButton_close")
        self.gridLayout_2.addWidget(self.pushButton_close, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_button, 2, 0, 1, 1)
        self.frame_message = QtWidgets.QFrame(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_message.setFont(font)
        self.frame_message.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_message.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_message.setObjectName("frame_message")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_message)
        self.gridLayout_4.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_message)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 284, 82))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_message = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_message.setMinimumSize(QtCore.QSize(0, 0))
        self.label_message.setMaximumSize(QtCore.QSize(650, 1200))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_message.setFont(font)
        self.label_message.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_message.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_message.setTextFormat(QtCore.Qt.AutoText)
        self.label_message.setAlignment(QtCore.Qt.AlignCenter)
        self.label_message.setWordWrap(True)
        self.label_message.setIndent(-1)
        self.label_message.setObjectName("label_message")
        self.gridLayout_5.addWidget(self.label_message, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_message, 1, 0, 1, 1)
        self.frame_title = QtWidgets.QFrame(Dialog)
        self.frame_title.setMinimumSize(QtCore.QSize(0, 42))
        self.frame_title.setMaximumSize(QtCore.QSize(650, 42))
        self.frame_title.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_title)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_title = QtWidgets.QLabel(self.frame_title)
        self.label_title.setMinimumSize(QtCore.QSize(0, 0))
        self.label_title.setMaximumSize(QtCore.QSize(620, 36))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("")
        self.label_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_title.setTextFormat(QtCore.Qt.AutoText)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_title, 0, 0, 1, 1)
        self.frame_progress_bar = QtWidgets.QFrame(Dialog)
        self.frame_progress_bar.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_progress_bar.setMaximumSize(QtCore.QSize(650, 40))
        self.frame_progress_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_progress_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_progress_bar.setObjectName("frame_progress_bar")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_progress_bar)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.progress_bar_timer = QtWidgets.QProgressBar(self.frame_progress_bar)
        self.progress_bar_timer.setMaximumSize(QtCore.QSize(240, 16777215))
        self.progress_bar_timer.setStyleSheet("QProgressBar { border-radius: 4px;  background-color: rgb(255,255,255);  border-width: 1px}\n"
"QProgressBar::chunk {border-radius: 4px;   background-color:  rgb(20,150,255);  border-width: 1px }")
        self.progress_bar_timer.setProperty("value", 0)
        self.progress_bar_timer.setTextVisible(False)
        self.progress_bar_timer.setObjectName("progress_bar_timer")
        self.gridLayout_6.addWidget(self.progress_bar_timer, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_progress_bar, 3, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_close.setText(_translate("Dialog", "Close"))
        self.label_message.setText(_translate("Dialog", "< message >"))
        self.label_title.setText(_translate("Dialog", "Title"))


class PrintMessage_UI(QtWidgets.QDialog, Ui_Dialog):
    """
    Component Hierarchy:
    - Dialog: QDialog
        - (Layout): QGridLayout
                - frame_button: QFrame
                    - (Layout): QGridLayout
                            - pushButton_close: QPushButton
                - frame_message: QFrame
                    - (Layout): QGridLayout
                            - scrollArea: QScrollArea
                                - scrollAreaWidgetContents: QWidget
                                    - (Layout): QGridLayout
                                            - label_message: QLabel
                - frame_title: QFrame
                    - (Layout): QGridLayout
                            - label_title: QLabel
                - frame_progress_bar: QFrame
                    - (Layout): QGridLayout
                            - progress_bar_timer: QProgressBar
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setupUi(self)
