[tool.poetry]
name = "vibra"
version = "0.2.4"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
numpy = ">=1.26"
vtk = "^9.4.0"
gmsh = "^4.11.1"
ctrefprop = "^0.10.2"
scipy = "^1.11.1"
pandas = "^2.1.0"
openpyxl = "^3.1.2"
mkl = "2023.2.0"
intel-openmp = "2023.2.0"
h5py = "^3.12.1"
moviepy = "^1.0.3"
pypardiso-mopt = "^0.1.0"
fileboxes = "^0.1.4"
molde = { git = "https://github.com/andrefpf/molde.git", branch = "update_dependencies" }
pyside6 = "^6.8.2.1"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
pytest = "^7.2.2"
isort = "^5.12.0"
pyinstaller = { version = "^6.4.0", python = ">=3.10,<3.14" }
tuna = "^0.5.11"

[tool.poetry.scripts]
vibra = "vibra.launch:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100

[tool.isort]
multi_line_output = 3
include_trailing_comma = true

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "serial",
]
