[project]
name = "vibra"
version = "0.4.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
    "numpy (>=2.2.6,<3.0.0)",
    "vtk (>=9.4.2,<9.5)",
    "gmsh (>=4.13.1,<5.0.0)",
    "ctrefprop (>=0.10.5,<0.11.0)",
    "scipy (>=1.15.3,<2.0.0)",
    "pandas (>=2.2.3,<3.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)",
    "mkl (>=2025.1.0,<2026.0.0)",
    "intel-openmp (>=2025.1.1,<2026.0.0)",
    "h5py (>=3.13.0,<4.0.0)",
    "moviepy (>=1.0.3,<2.0.0)",
    "pypardiso-mopt (>=0.1.0,<0.2.0)",
    "fileboxes (>=0.1.4,<0.2.0)",
    "molde (==0.1.17)",
    "pyside6 (==6.9.2)",
]


[tool.poetry]

[tool.poetry.group.dev.dependencies]
ruff = "^0.11.10"
pytest = "^8.3.5"
pytest-datadir = "^1.7.2"
pyinstaller = "^6.13.0"
tuna = "^0.5.11"
invoke = "^2.2.0"

[tool.poetry.scripts]
vibra = "vibra.launch:main"

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "serial",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"