# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analysis/general/analysis_type_input.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(360, 380)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(360, 380))
        Dialog.setMaximumSize(QtCore.QSize(360, 380))
        Dialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/gustavo/VRU/VIBRA/vibra/interface/data/ui_files/analysis/general/../../../../../Downloads/load - Copia.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setWhatsThis("")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_title = QtWidgets.QFrame(Dialog)
        self.frame_title.setMinimumSize(QtCore.QSize(0, 48))
        self.frame_title.setMaximumSize(QtCore.QSize(420, 48))
        self.frame_title.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_title.setLineWidth(1)
        self.frame_title.setObjectName("frame_title")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_title)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_title, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setEnabled(True)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(420, 400))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_harmonic_structural = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_harmonic_structural.setEnabled(True)
        self.pushButton_harmonic_structural.setMinimumSize(QtCore.QSize(240, 36))
        self.pushButton_harmonic_structural.setMaximumSize(QtCore.QSize(240, 36))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_harmonic_structural.setFont(font)
        self.pushButton_harmonic_structural.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/home/gustavo/VRU/VIBRA/vibra/interface/data/ui_files/analysis/general/../../../../../Downloads/load.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.pushButton_harmonic_structural.setIcon(icon1)
        self.pushButton_harmonic_structural.setShortcut("")
        self.pushButton_harmonic_structural.setAutoDefault(True)
        self.pushButton_harmonic_structural.setDefault(False)
        self.pushButton_harmonic_structural.setFlat(False)
        self.pushButton_harmonic_structural.setObjectName("pushButton_harmonic_structural")
        self.gridLayout_3.addWidget(self.pushButton_harmonic_structural, 0, 0, 1, 1)
        self.pushButton_harmonic_acoustic = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_harmonic_acoustic.setMinimumSize(QtCore.QSize(240, 36))
        self.pushButton_harmonic_acoustic.setMaximumSize(QtCore.QSize(240, 36))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_harmonic_acoustic.setFont(font)
        self.pushButton_harmonic_acoustic.setStyleSheet("")
        self.pushButton_harmonic_acoustic.setObjectName("pushButton_harmonic_acoustic")
        self.gridLayout_3.addWidget(self.pushButton_harmonic_acoustic, 1, 0, 1, 1)
        self.pushButton_harmonic_coupled = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_harmonic_coupled.setMinimumSize(QtCore.QSize(240, 36))
        self.pushButton_harmonic_coupled.setMaximumSize(QtCore.QSize(240, 36))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_harmonic_coupled.setFont(font)
        self.pushButton_harmonic_coupled.setStyleSheet("")
        self.pushButton_harmonic_coupled.setObjectName("pushButton_harmonic_coupled")
        self.gridLayout_3.addWidget(self.pushButton_harmonic_coupled, 2, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 3, 0, 1, 1)
        self.pushButton_modal_structural = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_modal_structural.setMinimumSize(QtCore.QSize(240, 36))
        self.pushButton_modal_structural.setMaximumSize(QtCore.QSize(240, 36))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_modal_structural.setFont(font)
        self.pushButton_modal_structural.setStyleSheet("")
        self.pushButton_modal_structural.setObjectName("pushButton_modal_structural")
        self.gridLayout_3.addWidget(self.pushButton_modal_structural, 4, 0, 1, 1)
        self.pushButton_modal_acoustic = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_modal_acoustic.setMinimumSize(QtCore.QSize(240, 36))
        self.pushButton_modal_acoustic.setMaximumSize(QtCore.QSize(240, 36))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_modal_acoustic.setFont(font)
        self.pushButton_modal_acoustic.setStyleSheet("")
        self.pushButton_modal_acoustic.setObjectName("pushButton_modal_acoustic")
        self.gridLayout_3.addWidget(self.pushButton_modal_acoustic, 5, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Select analysis type "))
        self.label.setText(_translate("Dialog", "Select the analysis type"))
        self.pushButton_harmonic_structural.setText(_translate("Dialog", "Harmonic Analysis - Structural"))
        self.pushButton_harmonic_acoustic.setText(_translate("Dialog", "Harmonic Analysis - Acoustic"))
        self.pushButton_harmonic_coupled.setText(_translate("Dialog", "Harmonic Analysis - Coupled"))
        self.pushButton_modal_structural.setText(_translate("Dialog", "Modal Analysis - Structural"))
        self.pushButton_modal_acoustic.setText(_translate("Dialog", "Modal Analysis - Acoustic"))


class AnalysisTypeInput_UI(QtWidgets.QDialog, Ui_Dialog):
    """
    Component Hierarchy:
    - Dialog: QDialog
        - (Layout): QGridLayout
                - frame_title: QFrame
                    - (Layout): QGridLayout
                            - label: QLabel
                - frame_2: QFrame
                    - (Layout): QGridLayout
                            - pushButton_harmonic_structural: QPushButton
                            - pushButton_harmonic_acoustic: QPushButton
                            - pushButton_harmonic_coupled: QPushButton
                            - line: Line
                            - pushButton_modal_structural: QPushButton
                            - pushButton_modal_acoustic: QPushButton
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setupUi(self)
