# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model/setup/material/material_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(720, 370)
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 48))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_attribute = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_attribute.setMinimumSize(QtCore.QSize(140, 32))
        self.pushButton_attribute.setMaximumSize(QtCore.QSize(160, 32))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_attribute.setFont(font)
        self.pushButton_attribute.setStyleSheet("")
        self.pushButton_attribute.setObjectName("pushButton_attribute")
        self.gridLayout_3.addWidget(self.pushButton_attribute, 0, 1, 1, 1)
        self.pushButton_exit = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_exit.setMinimumSize(QtCore.QSize(140, 32))
        self.pushButton_exit.setMaximumSize(QtCore.QSize(160, 32))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setStyleSheet("")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.gridLayout_3.addWidget(self.pushButton_exit, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_3, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_2.setHorizontalSpacing(4)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget_material_data = QtWidgets.QTableWidget(self.frame_2)
        self.tableWidget_material_data.setObjectName("tableWidget_material_data")
        self.tableWidget_material_data.setColumnCount(0)
        self.tableWidget_material_data.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_material_data.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_material_data.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_material_data.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_material_data.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_material_data.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_material_data.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget_material_data.setVerticalHeaderItem(6, item)
        self.tableWidget_material_data.horizontalHeader().setVisible(False)
        self.tableWidget_material_data.verticalHeader().setVisible(True)
        self.tableWidget_material_data.verticalHeader().setCascadingSectionResizes(True)
        self.gridLayout_2.addWidget(self.tableWidget_material_data, 1, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(8)
        self.gridLayout_5.setVerticalSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_remove_column = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_remove_column.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_remove_column.setMaximumSize(QtCore.QSize(26, 26))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_remove_column.setFont(font)
        self.pushButton_remove_column.setStyleSheet("")
        self.pushButton_remove_column.setObjectName("pushButton_remove_column")
        self.gridLayout_5.addWidget(self.pushButton_remove_column, 0, 3, 1, 1)
        self.pushButton_add_column = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_add_column.setMinimumSize(QtCore.QSize(26, 26))
        self.pushButton_add_column.setMaximumSize(QtCore.QSize(26, 26))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_add_column.setFont(font)
        self.pushButton_add_column.setStyleSheet("")
        self.pushButton_add_column.setObjectName("pushButton_add_column")
        self.gridLayout_5.addWidget(self.pushButton_add_column, 0, 2, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_reset_library = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_reset_library.setMinimumSize(QtCore.QSize(60, 26))
        self.pushButton_reset_library.setMaximumSize(QtCore.QSize(60, 26))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_reset_library.setFont(font)
        self.pushButton_reset_library.setStyleSheet("")
        self.pushButton_reset_library.setObjectName("pushButton_reset_library")
        self.gridLayout.addWidget(self.pushButton_reset_library, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame_7, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_6, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_attribute.setToolTip(_translate("Form", "<html><head/><body><p>Confirm material attribution</p></body></html>"))
        self.pushButton_attribute.setText(_translate("Form", "Attribute material"))
        self.pushButton_exit.setToolTip(_translate("Form", "<html><head/><body><p>Confirm material attribution</p></body></html>"))
        self.pushButton_exit.setText(_translate("Form", "Exit"))
        item = self.tableWidget_material_data.verticalHeaderItem(0)
        item.setText(_translate("Form", "Name"))
        item = self.tableWidget_material_data.verticalHeaderItem(1)
        item.setText(_translate("Form", "ID"))
        item = self.tableWidget_material_data.verticalHeaderItem(2)
        item.setText(_translate("Form", "Density [kg/m³]"))
        item = self.tableWidget_material_data.verticalHeaderItem(3)
        item.setText(_translate("Form", "Elasticity modulus [GPa]"))
        item = self.tableWidget_material_data.verticalHeaderItem(4)
        item.setText(_translate("Form", "Poisson"))
        item = self.tableWidget_material_data.verticalHeaderItem(5)
        item.setText(_translate("Form", "Thermal expansion coefficient [1/K]"))
        item = self.tableWidget_material_data.verticalHeaderItem(6)
        item.setText(_translate("Form", "Color"))
        self.pushButton_remove_column.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:400;\">Remove selected row</span></p></body></html>"))
        self.pushButton_remove_column.setText(_translate("Form", "-"))
        self.pushButton_add_column.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:400;\">Add row</span></p></body></html>"))
        self.pushButton_add_column.setText(_translate("Form", "+"))
        self.pushButton_reset_library.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-weight:400;\">Reset to default material library</span></p></body></html>"))
        self.pushButton_reset_library.setText(_translate("Form", "Reset"))


class MaterialWidget_UI(QtWidgets.QWidget, Ui_Form):
    """
    Component Hierarchy:
    - Form: QWidget
        - (Layout): QGridLayout
                - frame_3: QFrame
                    - (Layout): QGridLayout
                            - pushButton_attribute: QPushButton
                            - pushButton_exit: QPushButton
                - frame_2: QFrame
                    - (Layout): QGridLayout
                            - tableWidget_material_data: QTableWidget
                            - frame_6: QFrame
                                - (Layout): QGridLayout
                                        - pushButton_remove_column: QPushButton
                                        - pushButton_add_column: QPushButton
                                        - frame_7: QFrame
                                            - (Layout): QGridLayout
                                                    - pushButton_reset_library: QPushButton
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setupUi(self)
