# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model/setup/fluid/load_fluid_composition.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 260)
        Dialog.setMinimumSize(QtCore.QSize(500, 260))
        Dialog.setMaximumSize(QtCore.QSize(500, 260))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setMinimumSize(QtCore.QSize(0, 48))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 48))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_2.setSpacing(4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setContentsMargins(12, 4, 12, 4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_file_path = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_file_path.setMinimumSize(QtCore.QSize(300, 30))
        self.lineEdit_file_path.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_file_path.setFont(font)
        self.lineEdit_file_path.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_file_path.setObjectName("lineEdit_file_path")
        self.gridLayout_4.addWidget(self.lineEdit_file_path, 0, 0, 1, 1)
        self.pushButton_search = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_search.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton_search.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_search.setFont(font)
        self.pushButton_search.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/new_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_search.setIcon(icon)
        self.pushButton_search.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_search.setObjectName("pushButton_search")
        self.gridLayout_4.addWidget(self.pushButton_search, 0, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_sheet_name = QtWidgets.QLabel(self.frame_4)
        self.label_sheet_name.setMinimumSize(QtCore.QSize(0, 28))
        self.label_sheet_name.setMaximumSize(QtCore.QSize(100, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_sheet_name.setFont(font)
        self.label_sheet_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_sheet_name.setObjectName("label_sheet_name")
        self.gridLayout_5.addWidget(self.label_sheet_name, 0, 1, 1, 1)
        self.comboBox_sheet_names = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_sheet_names.setMinimumSize(QtCore.QSize(160, 28))
        self.comboBox_sheet_names.setMaximumSize(QtCore.QSize(160, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_sheet_names.setFont(font)
        self.comboBox_sheet_names.setObjectName("comboBox_sheet_names")
        self.gridLayout_5.addWidget(self.comboBox_sheet_names, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_4, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 48))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 48))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_exit = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_exit.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_exit.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.gridLayout_3.addWidget(self.pushButton_exit, 0, 0, 1, 1)
        self.pushButton_confirm = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_confirm.setMinimumSize(QtCore.QSize(90, 30))
        self.pushButton_confirm.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_confirm.setFont(font)
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.gridLayout_3.addWidget(self.pushButton_confirm, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Load fluid composition from file"))
        self.label_sheet_name.setText(_translate("Dialog", "Sheet name:"))
        self.pushButton_exit.setText(_translate("Dialog", "Exit"))
        self.pushButton_confirm.setText(_translate("Dialog", "Confirm"))


class LoadFluidComposition_UI(QtWidgets.QDialog, Ui_Dialog):
    """
    Component Hierarchy:
    - Dialog: QDialog
        - (Layout): QGridLayout
                - frame: QFrame
                    - (Layout): QGridLayout
                            - label: QLabel
                - frame_3: QFrame
                    - (Layout): QGridLayout
                            - lineEdit_file_path: QLineEdit
                            - pushButton_search: QPushButton
                            - frame_4: QFrame
                                - (Layout): QGridLayout
                                        - label_sheet_name: QLabel
                                        - comboBox_sheet_names: QComboBox
                - frame_2: QFrame
                    - (Layout): QGridLayout
                            - pushButton_exit: QPushButton
                            - pushButton_confirm: QPushButton
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setupUi(self)
