# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model/setup/fluid/set_fluid_input.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(780, 650)
        Dialog.setMinimumSize(QtCore.QSize(600, 300))
        Dialog.setMaximumSize(QtCore.QSize(1000, 720))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_main_widget = QtWidgets.QFrame(Dialog)
        self.frame_main_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_main_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_main_widget.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_main_widget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main_widget.setObjectName("frame_main_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_main_widget)
        self.gridLayout_3.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea_table_of_fluids = QtWidgets.QScrollArea(self.frame_main_widget)
        self.scrollArea_table_of_fluids.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_table_of_fluids.setWidgetResizable(True)
        self.scrollArea_table_of_fluids.setObjectName("scrollArea_table_of_fluids")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 764, 510))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_table_of_fluids.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea_table_of_fluids, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame_main_widget)
        self.frame_2.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.comboBox_attribution_type = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_attribution_type.setMinimumSize(QtCore.QSize(0, 26))
        self.comboBox_attribution_type.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_attribution_type.setFont(font)
        self.comboBox_attribution_type.setObjectName("comboBox_attribution_type")
        self.comboBox_attribution_type.addItem("")
        self.comboBox_attribution_type.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_attribution_type, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 1, 1, 1)
        self.lineEdit_selection_id = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_selection_id.setEnabled(True)
        self.lineEdit_selection_id.setMinimumSize(QtCore.QSize(180, 26))
        self.lineEdit_selection_id.setMaximumSize(QtCore.QSize(180, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_selection_id.setFont(font)
        self.lineEdit_selection_id.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_selection_id.setStyleSheet("QLineEdit{background-color: rgb(255, 255, 255); color: rgb(0, 0, 0)}\n"
"QLineEdit:disabled {background-color: rgb(230, 230, 230); color: rgb(120, 120, 120)}")
        self.lineEdit_selection_id.setText("")
        self.lineEdit_selection_id.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_selection_id.setObjectName("lineEdit_selection_id")
        self.gridLayout_4.addWidget(self.lineEdit_selection_id, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 1, 1, 1)
        self.lineEdit_selected_fluid_name = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_selected_fluid_name.setEnabled(False)
        self.lineEdit_selected_fluid_name.setMinimumSize(QtCore.QSize(180, 26))
        self.lineEdit_selected_fluid_name.setMaximumSize(QtCore.QSize(180, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_selected_fluid_name.setFont(font)
        self.lineEdit_selected_fluid_name.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_selected_fluid_name.setStyleSheet("QLineEdit{background-color: rgb(255, 255, 255); color: rgb(0, 0, 0)}\n"
"QLineEdit:disabled {background-color: rgb(230, 230, 230); color: rgb(120, 120, 120)}")
        self.lineEdit_selected_fluid_name.setText("")
        self.lineEdit_selected_fluid_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_selected_fluid_name.setObjectName("lineEdit_selected_fluid_name")
        self.gridLayout_4.addWidget(self.lineEdit_selected_fluid_name, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_main_widget, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setMinimumSize(QtCore.QSize(400, 48))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 48))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.comboBox_attribution_type.setItemText(0, _translate("Dialog", " All bodies"))
        self.comboBox_attribution_type.setItemText(1, _translate("Dialog", " Selected bodies"))
        self.label_4.setText(_translate("Dialog", "Selected fluid:"))
        self.label_2.setText(_translate("Dialog", "Selected bodies:"))
        self.label.setText(_translate("Dialog", "Set fluid configuration"))


class SetFluidInput_UI(QtWidgets.QDialog, Ui_Dialog):
    """
    Component Hierarchy:
    - Dialog: QDialog
        - (Layout): QGridLayout
                - frame_main_widget: QFrame
                    - (Layout): QGridLayout
                            - scrollArea_table_of_fluids: QScrollArea
                                - scrollAreaWidgetContents: QWidget
                            - frame_2: QFrame
                                - (Layout): QGridLayout
                                        - comboBox_attribution_type: QComboBox
                                        - label_4: QLabel
                                        - lineEdit_selection_id: QLineEdit
                                        - label_2: QLabel
                                        - lineEdit_selected_fluid_name: QLineEdit
                - frame: QFrame
                    - (Layout): QGridLayout
                            - label: QLabel
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setupUi(self)
