# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_handler/export_mesh.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(357, 280)
        Dialog.setMinimumSize(QtCore.QSize(0, 280))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 280))
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.checkBox_nodal_coordinates = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_nodal_coordinates.setMaximumSize(QtCore.QSize(260, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_nodal_coordinates.setFont(font)
        self.checkBox_nodal_coordinates.setObjectName("checkBox_nodal_coordinates")
        self.gridLayout_2.addWidget(self.checkBox_nodal_coordinates, 0, 1, 1, 1)
        self.checkBox_face_elements_connectivity = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_face_elements_connectivity.setMaximumSize(QtCore.QSize(260, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_face_elements_connectivity.setFont(font)
        self.checkBox_face_elements_connectivity.setObjectName("checkBox_face_elements_connectivity")
        self.gridLayout_2.addWidget(self.checkBox_face_elements_connectivity, 1, 1, 1, 1)
        self.checkBox_export_vtu_file = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_export_vtu_file.setMaximumSize(QtCore.QSize(260, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_export_vtu_file.setFont(font)
        self.checkBox_export_vtu_file.setObjectName("checkBox_export_vtu_file")
        self.gridLayout_2.addWidget(self.checkBox_export_vtu_file, 4, 1, 1, 1)
        self.checkBox_solid_elements_connectivity = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_solid_elements_connectivity.setMaximumSize(QtCore.QSize(260, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_solid_elements_connectivity.setFont(font)
        self.checkBox_solid_elements_connectivity.setObjectName("checkBox_solid_elements_connectivity")
        self.gridLayout_2.addWidget(self.checkBox_solid_elements_connectivity, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 2, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 48))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_export_mesh = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_export_mesh.setMinimumSize(QtCore.QSize(120, 30))
        self.pushButton_export_mesh.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_export_mesh.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_export_mesh.setIcon(icon)
        self.pushButton_export_mesh.setAutoDefault(False)
        self.pushButton_export_mesh.setObjectName("pushButton_export_mesh")
        self.gridLayout_5.addWidget(self.pushButton_export_mesh, 0, 1, 1, 1)
        self.pushButton_exit = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_exit.setMinimumSize(QtCore.QSize(120, 30))
        self.pushButton_exit.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_exit.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_exit.setIcon(icon1)
        self.pushButton_exit.setAutoDefault(False)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.gridLayout_5.addWidget(self.pushButton_exit, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_4, 3, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_6.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_6.setSpacing(4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit_folder_path = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_folder_path.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_folder_path.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_folder_path.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_folder_path.setObjectName("lineEdit_folder_path")
        self.gridLayout_6.addWidget(self.lineEdit_folder_path, 0, 0, 1, 1)
        self.pushButton_search_folder = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_search_folder.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton_search_folder.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_search_folder.setFont(font)
        self.pushButton_search_folder.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/views/zoom_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_search_folder.setIcon(icon2)
        self.pushButton_search_folder.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_search_folder.setAutoDefault(False)
        self.pushButton_search_folder.setObjectName("pushButton_search_folder")
        self.gridLayout_6.addWidget(self.pushButton_search_folder, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame_5, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 48))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setMinimumSize(QtCore.QSize(0, 26))
        self.label.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit_folder_path, self.pushButton_search_folder)
        Dialog.setTabOrder(self.pushButton_search_folder, self.checkBox_nodal_coordinates)
        Dialog.setTabOrder(self.checkBox_nodal_coordinates, self.checkBox_face_elements_connectivity)
        Dialog.setTabOrder(self.checkBox_face_elements_connectivity, self.checkBox_solid_elements_connectivity)
        Dialog.setTabOrder(self.checkBox_solid_elements_connectivity, self.checkBox_export_vtu_file)
        Dialog.setTabOrder(self.checkBox_export_vtu_file, self.pushButton_export_mesh)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Export mesh data"))
        self.checkBox_nodal_coordinates.setToolTip(_translate("Dialog", "<html><head/><body><p>The nodal coordinates will be exported to the &quot;nodal_coordinates.dat&quot; file.</p></body></html>"))
        self.checkBox_nodal_coordinates.setText(_translate("Dialog", "Nodal coordinates"))
        self.checkBox_face_elements_connectivity.setToolTip(_translate("Dialog", "<html><head/><body><p>The face elements connectivity data will be exported to the &quot;face_elements_connectivity.dat&quot; file.</p></body></html>"))
        self.checkBox_face_elements_connectivity.setText(_translate("Dialog", "Face elements connectivity"))
        self.checkBox_export_vtu_file.setToolTip(_translate("Dialog", "<html><head/><body><p>The mesh data will be exported to the &quot;mesh_data.vtu&quot; file.</p></body></html>"))
        self.checkBox_export_vtu_file.setText(_translate("Dialog", "Paraview compatible format"))
        self.checkBox_solid_elements_connectivity.setToolTip(_translate("Dialog", "<html><head/><body><p>The solid elements connectivity data will be exported to the &quot;solid_elements_connectivity.dat&quot; file.</p></body></html>"))
        self.checkBox_solid_elements_connectivity.setText(_translate("Dialog", "Solid elements connectivity"))
        self.pushButton_export_mesh.setText(_translate("Dialog", " Export mesh"))
        self.pushButton_exit.setText(_translate("Dialog", "Exit"))
        self.label.setText(_translate("Dialog", "Mesh data export assistant"))


class ExportMesh_UI(QtWidgets.QDialog, Ui_Dialog):
    """
    Component Hierarchy:
    - Dialog: QDialog
        - (Layout): QGridLayout
                - frame: QFrame
                    - (Layout): QGridLayout
                            - frame_2: QFrame
                                - (Layout): QGridLayout
                                        - checkBox_nodal_coordinates: QCheckBox
                                        - checkBox_face_elements_connectivity: QCheckBox
                                        - checkBox_export_vtu_file: QCheckBox
                                        - checkBox_solid_elements_connectivity: QCheckBox
                            - frame_4: QFrame
                                - (Layout): QGridLayout
                                        - pushButton_export_mesh: QPushButton
                                        - pushButton_exit: QPushButton
                            - frame_5: QFrame
                                - (Layout): QGridLayout
                                        - lineEdit_folder_path: QLineEdit
                                        - pushButton_search_folder: QPushButton
                - frame_3: QFrame
                    - (Layout): QGridLayout
                            - label: QLabel
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setupUi(self)
