# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project/save_project_data_selector.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(340, 260)
        Dialog.setMinimumSize(QtCore.QSize(340, 260))
        Dialog.setMaximumSize(QtCore.QSize(340, 260))
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_solution_data = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_solution_data.setMinimumSize(QtCore.QSize(0, 28))
        self.checkBox_solution_data.setMaximumSize(QtCore.QSize(260, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_solution_data.setFont(font)
        self.checkBox_solution_data.setChecked(True)
        self.checkBox_solution_data.setObjectName("checkBox_solution_data")
        self.gridLayout_2.addWidget(self.checkBox_solution_data, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.checkBox_mesh_data = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_mesh_data.setMinimumSize(QtCore.QSize(0, 28))
        self.checkBox_mesh_data.setMaximumSize(QtCore.QSize(260, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_mesh_data.setFont(font)
        self.checkBox_mesh_data.setChecked(True)
        self.checkBox_mesh_data.setObjectName("checkBox_mesh_data")
        self.gridLayout_2.addWidget(self.checkBox_mesh_data, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 2, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_6.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_6.setHorizontalSpacing(6)
        self.gridLayout_6.setVerticalSpacing(4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setMinimumSize(QtCore.QSize(0, 28))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setMinimumSize(QtCore.QSize(0, 28))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 0, 3, 1, 1)
        self.lineEdit_required_memory = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_required_memory.setMinimumSize(QtCore.QSize(100, 28))
        self.lineEdit_required_memory.setMaximumSize(QtCore.QSize(100, 28))
        self.lineEdit_required_memory.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_required_memory.setObjectName("lineEdit_required_memory")
        self.gridLayout_6.addWidget(self.lineEdit_required_memory, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 0, 4, 1, 1)
        self.gridLayout_4.addWidget(self.frame_5, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 48))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setMinimumSize(QtCore.QSize(0, 26))
        self.label.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(Dialog)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 48))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_proceed = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_proceed.setMinimumSize(QtCore.QSize(120, 30))
        self.pushButton_proceed.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_proceed.setFont(font)
        self.pushButton_proceed.setAutoDefault(False)
        self.pushButton_proceed.setObjectName("pushButton_proceed")
        self.gridLayout_5.addWidget(self.pushButton_proceed, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_4, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.checkBox_mesh_data, self.checkBox_solution_data)
        Dialog.setTabOrder(self.checkBox_solution_data, self.pushButton_proceed)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Project data to save"))
        self.checkBox_solution_data.setToolTip(_translate("Dialog", "<html><head/><body><p>Save the solution data</p></body></html>"))
        self.checkBox_solution_data.setText(_translate("Dialog", "Solution data"))
        self.checkBox_mesh_data.setToolTip(_translate("Dialog", "<html><head/><body><p>Save the mesh data</p></body></html>"))
        self.checkBox_mesh_data.setText(_translate("Dialog", "Mesh data"))
        self.label_2.setText(_translate("Dialog", "Required memory:"))
        self.label_3.setText(_translate("Dialog", "[MB]"))
        self.label.setText(_translate("Dialog", "Project data to save"))
        self.pushButton_proceed.setText(_translate("Dialog", "Proceed"))


class SaveProjectDataSelector_UI(QtWidgets.QDialog, Ui_Dialog):
    """
    Component Hierarchy:
    - Dialog: QDialog
        - (Layout): QGridLayout
                - frame: QFrame
                    - (Layout): QGridLayout
                            - frame_2: QFrame
                                - (Layout): QGridLayout
                                        - checkBox_solution_data: QCheckBox
                                        - checkBox_mesh_data: QCheckBox
                            - frame_5: QFrame
                                - (Layout): QGridLayout
                                        - label_2: QLabel
                                        - label_3: QLabel
                                        - lineEdit_required_memory: QLineEdit
                - frame_3: QFrame
                    - (Layout): QGridLayout
                            - label: QLabel
                - frame_4: QFrame
                    - (Layout): QGridLayout
                            - pushButton_proceed: QPushButton
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setupUi(self)
