from enum import Enum


class AnalysisID(Enum):
    NO_ANALYSIS = -1
    STRUCTURAL_HARMONIC_DIRECT_METHOD = 0
    STRUCTURAL_HARMONIC_MODE_SUPERPOSITION = 1
    STRUCTURAL_MODAL = 2
    ACOUSTIC_HARMONIC = 3
    ACOUSTIC_MODAL = 4
    COUPLED_HARMONIC_DIRECT_METHOD = 5
    COUPLED_HARMONIC_MODE_SUPERPOSITION = 6
    STATIC_ANALYSIS = 7
