# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model/setup/acoustic/get_sphere_selection_information.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(420, 320)
        Dialog.setMinimumSize(QtCore.QSize(420, 320))
        Dialog.setMaximumSize(QtCore.QSize(420, 320))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 48))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setMinimumSize(QtCore.QSize(160, 0))
        self.label_2.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 3, 1, 1, 1)
        self.lineEdit_coordinate_x = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_coordinate_x.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_coordinate_x.setMaximumSize(QtCore.QSize(140, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_coordinate_x.setFont(font)
        self.lineEdit_coordinate_x.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_coordinate_x.setObjectName("lineEdit_coordinate_x")
        self.gridLayout_4.addWidget(self.lineEdit_coordinate_x, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setMinimumSize(QtCore.QSize(160, 0))
        self.label_10.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setMinimumSize(QtCore.QSize(34, 0))
        self.label_11.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setMinimumSize(QtCore.QSize(160, 0))
        self.label_14.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setMinimumSize(QtCore.QSize(160, 0))
        self.label_12.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 1, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        self.label_15.setMinimumSize(QtCore.QSize(34, 0))
        self.label_15.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 2, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setMinimumSize(QtCore.QSize(34, 0))
        self.label_13.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 1, 3, 1, 1)
        self.lineEdit_selection_radius = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_selection_radius.setMaximumSize(QtCore.QSize(140, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_selection_radius.setFont(font)
        self.lineEdit_selection_radius.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_selection_radius.setObjectName("lineEdit_selection_radius")
        self.gridLayout_4.addWidget(self.lineEdit_selection_radius, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setMinimumSize(QtCore.QSize(160, 0))
        self.label_3.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 3, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 0, 1, 1)
        self.lineEdit_coordinate_y = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_coordinate_y.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_coordinate_y.setMaximumSize(QtCore.QSize(140, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_coordinate_y.setFont(font)
        self.lineEdit_coordinate_y.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_coordinate_y.setObjectName("lineEdit_coordinate_y")
        self.gridLayout_4.addWidget(self.lineEdit_coordinate_y, 1, 2, 1, 1)
        self.lineEdit_coordinate_z = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_coordinate_z.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_coordinate_z.setMaximumSize(QtCore.QSize(140, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_coordinate_z.setFont(font)
        self.lineEdit_coordinate_z.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_coordinate_z.setObjectName("lineEdit_coordinate_z")
        self.gridLayout_4.addWidget(self.lineEdit_coordinate_z, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setMinimumSize(QtCore.QSize(160, 0))
        self.label_6.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 5, 1, 1, 1)
        self.lineEdit_number_of_elements = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_number_of_elements.setMaximumSize(QtCore.QSize(140, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_number_of_elements.setFont(font)
        self.lineEdit_number_of_elements.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_number_of_elements.setObjectName("lineEdit_number_of_elements")
        self.gridLayout_4.addWidget(self.lineEdit_number_of_elements, 4, 2, 1, 1)
        self.lineEdit_number_of_nodes = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_number_of_nodes.setMaximumSize(QtCore.QSize(140, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_number_of_nodes.setFont(font)
        self.lineEdit_number_of_nodes.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_number_of_nodes.setObjectName("lineEdit_number_of_nodes")
        self.gridLayout_4.addWidget(self.lineEdit_number_of_nodes, 5, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 4, 1, 1)
        self.gridLayout_3.addWidget(self.frame_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Selection information"))
        self.label_2.setText(_translate("Dialog", "Selection radius:"))
        self.label_10.setText(_translate("Dialog", "Center coordinate x:"))
        self.label_11.setText(_translate("Dialog", "[m]"))
        self.label_14.setText(_translate("Dialog", "Center coordinate z:"))
        self.label_12.setText(_translate("Dialog", "Center coordinate y:"))
        self.label_15.setText(_translate("Dialog", "[m]"))
        self.label_13.setText(_translate("Dialog", "[m]"))
        self.label_3.setText(_translate("Dialog", "Number of elements:"))
        self.label_4.setText(_translate("Dialog", "[m]"))
        self.label_6.setText(_translate("Dialog", "Number of nodes:"))


class GetSphereSelectionInformation_UI(QtWidgets.QDialog, Ui_Dialog):
    """
    Component Hierarchy:
    - Dialog: QDialog
        - (Layout): QGridLayout
                - frame: QFrame
                    - (Layout): QGridLayout
                            - label: QLabel
                - frame_2: QFrame
                    - (Layout): QGridLayout
                            - frame_3: QFrame
                                - (Layout): QGridLayout
                                        - label_2: QLabel
                                        - lineEdit_coordinate_x: QLineEdit
                                        - label_10: QLabel
                                        - label_11: QLabel
                                        - label_14: QLabel
                                        - label_12: QLabel
                                        - label_15: QLabel
                                        - label_13: QLabel
                                        - lineEdit_selection_radius: QLineEdit
                                        - label_3: QLabel
                                        - label_4: QLabel
                                        - lineEdit_coordinate_y: QLineEdit
                                        - lineEdit_coordinate_z: QLineEdit
                                        - label_6: QLabel
                                        - lineEdit_number_of_elements: QLineEdit
                                        - lineEdit_number_of_nodes: QLineEdit
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setupUi(self)
