# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'general/call_double_confirmation_input.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(520, 320)
        Dialog.setMinimumSize(QtCore.QSize(520, 320))
        Dialog.setMaximumSize(QtCore.QSize(650, 600))
        Dialog.setModal(True)
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_3.setHorizontalSpacing(2)
        self.gridLayout_3.setVerticalSpacing(4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setMinimumSize(QtCore.QSize(500, 42))
        self.frame.setMaximumSize(QtCore.QSize(630, 42))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_title = QtWidgets.QLabel(self.frame)
        self.label_title.setMinimumSize(QtCore.QSize(500, 40))
        self.label_title.setMaximumSize(QtCore.QSize(630, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("font: 75  bold 12pt \"Arial\";")
        self.label_title.setFrameShape(QtWidgets.QFrame.Box)
        self.label_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_title.setLineWidth(1)
        self.label_title.setTextFormat(QtCore.Qt.AutoText)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.gridLayout_2.addWidget(self.label_title, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        self.label_message = QtWidgets.QLabel(Dialog)
        self.label_message.setMinimumSize(QtCore.QSize(500, 200))
        self.label_message.setMaximumSize(QtCore.QSize(630, 500))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_message.setFont(font)
        self.label_message.setFrameShape(QtWidgets.QFrame.Box)
        self.label_message.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_message.setLineWidth(1)
        self.label_message.setTextFormat(QtCore.Qt.AutoText)
        self.label_message.setAlignment(QtCore.Qt.AlignCenter)
        self.label_message.setObjectName("label_message")
        self.gridLayout_3.addWidget(self.label_message, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setMinimumSize(QtCore.QSize(500, 52))
        self.frame_3.setMaximumSize(QtCore.QSize(630, 52))
        self.frame_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setContentsMargins(2, 2, 2, 0)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_leftButton = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_leftButton.sizePolicy().hasHeightForWidth())
        self.pushButton_leftButton.setSizePolicy(sizePolicy)
        self.pushButton_leftButton.setMinimumSize(QtCore.QSize(160, 36))
        self.pushButton_leftButton.setMaximumSize(QtCore.QSize(120, 36))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_leftButton.setFont(font)
        self.pushButton_leftButton.setStyleSheet("QPushButton{border-radius: 16px; border-color: rgb(150, 150, 150); border-style: ridge; border-width: 2px; color: rgb(0, 0, 0); background-color: rgb(240, 240, 240); font: 75 bold 11pt \"MS Shell Dlg 2\"}\n"
"QPushButton:hover{border-radius: 16px; border-color: rgb(0, 170, 255); border-style: ridge; border-width: 2px; color: rgb(0, 0, 0); background-color: rgba(174, 213, 255, 100); font: 75 bold 11pt \"MS Shell Dlg 2\"}\n"
"QPushButton:pressed{border-radius: 16px; border-color: rgb(0, 170, 255); border-style: ridge; border-width: 3px; color: rgb(0, 0, 0); background-color: rgb(174, 213, 255); font: 75 bold 11pt \"MS Shell Dlg 2\"}")
        self.pushButton_leftButton.setAutoDefault(False)
        self.pushButton_leftButton.setDefault(False)
        self.pushButton_leftButton.setFlat(False)
        self.pushButton_leftButton.setObjectName("pushButton_leftButton")
        self.gridLayout.addWidget(self.pushButton_leftButton, 0, 0, 1, 1)
        self.pushButton_rightButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_rightButton.setMinimumSize(QtCore.QSize(160, 36))
        self.pushButton_rightButton.setMaximumSize(QtCore.QSize(120, 36))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_rightButton.setFont(font)
        self.pushButton_rightButton.setStyleSheet("QPushButton{border-radius: 16px; border-color: rgb(150, 150, 150); border-style: ridge; border-width: 2px; color: rgb(0, 0, 0); background-color: rgb(240, 240, 240); font: 75 bold 11pt \"MS Shell Dlg 2\"}\n"
"QPushButton:hover{border-radius: 16px; border-color: rgb(0, 170, 255); border-style: ridge; border-width: 2px; color: rgb(0, 0, 0); background-color: rgba(174, 213, 255, 100); font: 75 bold 11pt \"MS Shell Dlg 2\"}\n"
"QPushButton:pressed{border-radius: 16px; border-color: rgb(0, 170, 255); border-style: ridge; border-width: 3px; color: rgb(0, 0, 0); background-color: rgb(174, 213, 255); font: 75 bold 11pt \"MS Shell Dlg 2\"}")
        self.pushButton_rightButton.setAutoDefault(True)
        self.pushButton_rightButton.setDefault(False)
        self.pushButton_rightButton.setFlat(False)
        self.pushButton_rightButton.setObjectName("pushButton_rightButton")
        self.gridLayout.addWidget(self.pushButton_rightButton, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_3, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Message"))
        self.label_title.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">TITLE</span></p></body></html>"))
        self.label_message.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Confirmation message...</p></body></html>"))
        self.pushButton_leftButton.setText(_translate("Dialog", "Left button"))
        self.pushButton_rightButton.setText(_translate("Dialog", "Right button"))


class CallDoubleConfirmationInput_UI(QtWidgets.QDialog, Ui_Dialog):
    """
    Component Hierarchy:
    - Dialog: QDialog
        - (Layout): QGridLayout
                - frame: QFrame
                    - (Layout): QGridLayout
                            - label_title: QLabel
                - label_message: QLabel
                - frame_3: QFrame
                    - (Layout): QGridLayout
                            - pushButton_leftButton: QPushButton
                            - pushButton_rightButton: QPushButton
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setupUi(self)
