# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'general/print_messages.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 260)
        Dialog.setMinimumSize(QtCore.QSize(400, 260))
        Dialog.setMaximumSize(QtCore.QSize(600, 600))
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_3.setHorizontalSpacing(2)
        self.gridLayout_3.setVerticalSpacing(4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_title = QtWidgets.QFrame(Dialog)
        self.frame_title.setMinimumSize(QtCore.QSize(360, 0))
        self.frame_title.setMaximumSize(QtCore.QSize(580, 52))
        self.frame_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_title)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_title = QtWidgets.QLabel(self.frame_title)
        self.label_title.setMinimumSize(QtCore.QSize(360, 36))
        self.label_title.setMaximumSize(QtCore.QSize(580, 36))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setFrameShape(QtWidgets.QFrame.Box)
        self.label_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_title.setTextFormat(QtCore.Qt.AutoText)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_title, 0, 0, 1, 1)
        self.frame_button = QtWidgets.QFrame(Dialog)
        self.frame_button.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_button.setMaximumSize(QtCore.QSize(16777215, 52))
        self.frame_button.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button.setObjectName("frame_button")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_button)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_close = QtWidgets.QPushButton(self.frame_button)
        self.pushButton_close.setMinimumSize(QtCore.QSize(120, 36))
        self.pushButton_close.setMaximumSize(QtCore.QSize(120, 36))
        self.pushButton_close.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_close.setFont(font)
        self.pushButton_close.setStyleSheet("QPushButton{border-radius: 16px; border-color: rgb(150, 150, 150); border-style: ridge; border-width: 2px; color: rgb(0, 0, 0); background-color: rgb(240, 240, 240); font: 75 italic bold 14pt \"Arial\"}\n"
"QPushButton:hover{border-radius: 16px; border-color: rgb(0, 170, 255); border-style: ridge; border-width: 2px; color: rgb(0, 0, 0); background-color: rgba(174, 213, 255, 100); font: 75 italic bold 14pt \"Arial\"}\n"
"QPushButton:pressed{border-radius: 16px; border-color: rgb(0, 170, 255); border-style: ridge; border-width: 3px; color: rgb(0, 0, 0); background-color: rgb(174, 213, 255); font: 75 italic bold 14pt \"Arial\"}")
        self.pushButton_close.setDefault(False)
        self.pushButton_close.setFlat(False)
        self.pushButton_close.setObjectName("pushButton_close")
        self.gridLayout_2.addWidget(self.pushButton_close, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_button, 2, 0, 1, 1)
        self.frame_message = QtWidgets.QFrame(Dialog)
        self.frame_message.setMinimumSize(QtCore.QSize(360, 160))
        self.frame_message.setMaximumSize(QtCore.QSize(580, 16777215))
        self.frame_message.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_message.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_message.setObjectName("frame_message")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_message)
        self.gridLayout_4.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_message = QtWidgets.QLabel(self.frame_message)
        self.label_message.setMinimumSize(QtCore.QSize(340, 120))
        self.label_message.setMaximumSize(QtCore.QSize(560, 280))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_message.setFont(font)
        self.label_message.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_message.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_message.setTextFormat(QtCore.Qt.AutoText)
        self.label_message.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_message.setWordWrap(True)
        self.label_message.setIndent(-1)
        self.label_message.setObjectName("label_message")
        self.gridLayout_4.addWidget(self.label_message, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_message, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_title.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">TITLE</span></p></body></html>"))
        self.pushButton_close.setText(_translate("Dialog", "Close"))
        self.label_message.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">message</span></p></body></html>"))


class PrintMessages_UI(QtWidgets.QDialog, Ui_Dialog):
    """
    Component Hierarchy:
    - Dialog: QDialog
        - (Layout): QGridLayout
                - frame_title: QFrame
                    - (Layout): QGridLayout
                            - label_title: QLabel
                - frame_button: QFrame
                    - (Layout): QGridLayout
                            - pushButton_close: QPushButton
                - frame_message: QFrame
                    - (Layout): QGridLayout
                            - label_message: QLabel
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setupUi(self)
