# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analysis/acoustic/acoustic_modal_analysis_input.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(300, 220)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(300, 220))
        Dialog.setMaximumSize(QtCore.QSize(300, 220))
        Dialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/home/gustavo/VRU/VIBRA/vibra/interface/data/ui_files/analysis/acoustic/../../../../../../../OpenPulse/Downloads/load - Copia.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setWhatsThis("")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(4, 4, 4, 4)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_title = QtWidgets.QFrame(Dialog)
        self.frame_title.setMinimumSize(QtCore.QSize(0, 48))
        self.frame_title.setMaximumSize(QtCore.QSize(16777215, 48))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.frame_title.setFont(font)
        self.frame_title.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setLineWidth(1)
        self.frame_title.setObjectName("frame_title")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_title)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_title = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_title.setFont(font)
        self.label_title.setTextFormat(QtCore.Qt.AutoText)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.gridLayout_2.addWidget(self.label_title, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_title, 0, 0, 1, 1)
        self.frame_main = QtWidgets.QFrame(Dialog)
        self.frame_main.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_main)
        self.gridLayout_3.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_modes = QtWidgets.QFrame(self.frame_main)
        self.frame_modes.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_modes.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_modes.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_modes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_modes.setObjectName("frame_modes")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_modes)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem1, 0, 4, 1, 1)
        self.label_modes = QtWidgets.QLabel(self.frame_modes)
        self.label_modes.setMinimumSize(QtCore.QSize(60, 28))
        self.label_modes.setMaximumSize(QtCore.QSize(60, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_modes.setFont(font)
        self.label_modes.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_modes.setObjectName("label_modes")
        self.gridLayout_12.addWidget(self.label_modes, 0, 1, 1, 1)
        self.lineEdit_number_modes = QtWidgets.QLineEdit(self.frame_modes)
        self.lineEdit_number_modes.setMinimumSize(QtCore.QSize(80, 28))
        self.lineEdit_number_modes.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_number_modes.setFont(font)
        self.lineEdit_number_modes.setStyleSheet("")
        self.lineEdit_number_modes.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_number_modes.setObjectName("lineEdit_number_modes")
        self.gridLayout_12.addWidget(self.lineEdit_number_modes, 0, 2, 1, 1)
        self.label_spacing = QtWidgets.QLabel(self.frame_modes)
        self.label_spacing.setMinimumSize(QtCore.QSize(60, 28))
        self.label_spacing.setMaximumSize(QtCore.QSize(60, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_spacing.setFont(font)
        self.label_spacing.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_spacing.setText("")
        self.label_spacing.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_spacing.setObjectName("label_spacing")
        self.gridLayout_12.addWidget(self.label_spacing, 0, 3, 1, 1)
        self.gridLayout_3.addWidget(self.frame_modes, 0, 0, 1, 1)
        self.frame_sigma = QtWidgets.QFrame(self.frame_main)
        self.frame_sigma.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_sigma.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_sigma.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_sigma.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_sigma.setObjectName("frame_sigma")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_sigma)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 0, 1, 1)
        self.label_sigma_unit = QtWidgets.QLabel(self.frame_sigma)
        self.label_sigma_unit.setMinimumSize(QtCore.QSize(60, 28))
        self.label_sigma_unit.setMaximumSize(QtCore.QSize(60, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_sigma_unit.setFont(font)
        self.label_sigma_unit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_sigma_unit.setObjectName("label_sigma_unit")
        self.gridLayout_4.addWidget(self.label_sigma_unit, 0, 3, 1, 1)
        self.label_sigma = QtWidgets.QLabel(self.frame_sigma)
        self.label_sigma.setMinimumSize(QtCore.QSize(60, 28))
        self.label_sigma.setMaximumSize(QtCore.QSize(60, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_sigma.setFont(font)
        self.label_sigma.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_sigma.setObjectName("label_sigma")
        self.gridLayout_4.addWidget(self.label_sigma, 0, 1, 1, 1)
        self.lineEdit_sigma_factor = QtWidgets.QLineEdit(self.frame_sigma)
        self.lineEdit_sigma_factor.setMinimumSize(QtCore.QSize(80, 28))
        self.lineEdit_sigma_factor.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_sigma_factor.setFont(font)
        self.lineEdit_sigma_factor.setStyleSheet("")
        self.lineEdit_sigma_factor.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_sigma_factor.setObjectName("lineEdit_sigma_factor")
        self.gridLayout_4.addWidget(self.lineEdit_sigma_factor, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 4, 1, 1)
        self.gridLayout_3.addWidget(self.frame_sigma, 1, 0, 1, 1)
        self.frame_button = QtWidgets.QFrame(self.frame_main)
        self.frame_button.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_button.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button.setObjectName("frame_button")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_button)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.pushButton_run_analysis = QtWidgets.QPushButton(self.frame_button)
        self.pushButton_run_analysis.setMinimumSize(QtCore.QSize(100, 28))
        self.pushButton_run_analysis.setMaximumSize(QtCore.QSize(100, 28))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_run_analysis.setFont(font)
        self.pushButton_run_analysis.setStyleSheet("")
        self.pushButton_run_analysis.setObjectName("pushButton_run_analysis")
        self.gridLayout_11.addWidget(self.pushButton_run_analysis, 0, 1, 1, 1)
        self.pushButton_enter_setup = QtWidgets.QPushButton(self.frame_button)
        self.pushButton_enter_setup.setMinimumSize(QtCore.QSize(100, 28))
        self.pushButton_enter_setup.setMaximumSize(QtCore.QSize(100, 28))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_enter_setup.setFont(font)
        self.pushButton_enter_setup.setStyleSheet("")
        self.pushButton_enter_setup.setObjectName("pushButton_enter_setup")
        self.gridLayout_11.addWidget(self.pushButton_enter_setup, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_button, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_main, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Modal analysis setup"))
        self.label_title.setText(_translate("Dialog", "Acoustic modal analysis"))
        self.label_modes.setText(_translate("Dialog", "Modes:"))
        self.lineEdit_number_modes.setToolTip(_translate("Dialog", "<html><head/><body><p>Number of modes to find in acoustic modal analysis</p></body></html>"))
        self.lineEdit_number_modes.setText(_translate("Dialog", "40"))
        self.label_sigma_unit.setText(_translate("Dialog", "[Hz]"))
        self.label_sigma.setText(_translate("Dialog", "Sigma:"))
        self.lineEdit_sigma_factor.setToolTip(_translate("Dialog", "<html><head/><body><p>This parameter allows to find eigenvalues near \'Sigma\' value using shift-invert mode.</p><p>&gt; See scipy.sparse.linalg.eigs for more details.</p></body></html>"))
        self.lineEdit_sigma_factor.setText(_translate("Dialog", "1e-2"))
        self.pushButton_run_analysis.setText(_translate("Dialog", "Run analysis"))
        self.pushButton_enter_setup.setText(_translate("Dialog", "Enter setup"))


class AcousticModalAnalysisInput_UI(QtWidgets.QDialog, Ui_Dialog):
    """
    Component Hierarchy:
    - Dialog: QDialog
        - (Layout): QGridLayout
                - frame_title: QFrame
                    - (Layout): QGridLayout
                            - label_title: QLabel
                - frame_main: QFrame
                    - (Layout): QGridLayout
                            - frame_modes: QFrame
                                - (Layout): QGridLayout
                                        - label_modes: QLabel
                                        - lineEdit_number_modes: QLineEdit
                                        - label_spacing: QLabel
                            - frame_sigma: QFrame
                                - (Layout): QGridLayout
                                        - label_sigma_unit: QLabel
                                        - label_sigma: QLabel
                                        - lineEdit_sigma_factor: QLineEdit
                            - frame_button: QFrame
                                - (Layout): QGridLayout
                                        - pushButton_run_analysis: QPushButton
                                        - pushButton_enter_setup: QPushButton
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setupUi(self)
