# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.9.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QHBoxLayout, QMainWindow, QMenu,
    QMenuBar, QSizePolicy, QSplitter, QStackedWidget,
    QStatusBar, QToolBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1055, 587)
        self.action_new_project = QAction(MainWindow)
        self.action_new_project.setObjectName(u"action_new_project")
        icon = QIcon()
        icon.addFile(u":/icons/new_file.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_new_project.setIcon(icon)
        self.action_open_project = QAction(MainWindow)
        self.action_open_project.setObjectName(u"action_open_project")
        icon1 = QIcon()
        icon1.addFile(u":/icons/import.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_open_project.setIcon(icon1)
        self.action_recent = QAction(MainWindow)
        self.action_recent.setObjectName(u"action_recent")
        icon2 = QIcon()
        icon2.addFile(u":/icons/recent.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_recent.setIcon(icon2)
        self.action_save = QAction(MainWindow)
        self.action_save.setObjectName(u"action_save")
        icon3 = QIcon()
        icon3.addFile(u":/icons/save.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_save.setIcon(icon3)
        self.action_save_as = QAction(MainWindow)
        self.action_save_as.setObjectName(u"action_save_as")
        icon4 = QIcon()
        icon4.addFile(u":/icons/save_as.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_save_as.setIcon(icon4)
        self.action_export_mesh = QAction(MainWindow)
        self.action_export_mesh.setObjectName(u"action_export_mesh")
        self.action_export_mesh.setIcon(icon3)
        self.action_capture_image = QAction(MainWindow)
        self.action_capture_image.setObjectName(u"action_capture_image")
        icon5 = QIcon()
        icon5.addFile(u":/icons/cube-scan.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_capture_image.setIcon(icon5)
        self.action_exit = QAction(MainWindow)
        self.action_exit.setObjectName(u"action_exit")
        icon6 = QIcon()
        icon6.addFile(u":/icons/exit.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_exit.setIcon(icon6)
        self.action_show_menu_items = QAction(MainWindow)
        self.action_show_menu_items.setObjectName(u"action_show_menu_items")
        self.action_show_menu_items.setIcon(icon)
        self.action_set_fluid = QAction(MainWindow)
        self.action_set_fluid.setObjectName(u"action_set_fluid")
        self.action_set_fluid.setIcon(icon)
        self.action_set_material = QAction(MainWindow)
        self.action_set_material.setObjectName(u"action_set_material")
        self.action_set_material.setIcon(icon)
        self.action_mesher_setup = QAction(MainWindow)
        self.action_mesher_setup.setObjectName(u"action_mesher_setup")
        self.action_mesher_setup.setIcon(icon)
        self.action_about_vibra = QAction(MainWindow)
        self.action_about_vibra.setObjectName(u"action_about_vibra")
        icon7 = QIcon()
        icon7.addFile(u":/icons/help.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_about_vibra.setIcon(icon7)
        self.action_reset_project = QAction(MainWindow)
        self.action_reset_project.setObjectName(u"action_reset_project")
        self.action_reset_project.setIcon(icon2)
        self.action_top_view = QAction(MainWindow)
        self.action_top_view.setObjectName(u"action_top_view")
        icon8 = QIcon()
        icon8.addFile(u":/icons/views/top.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_top_view.setIcon(icon8)
        self.action_bottom_view = QAction(MainWindow)
        self.action_bottom_view.setObjectName(u"action_bottom_view")
        icon9 = QIcon()
        icon9.addFile(u":/icons/views/bottom.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_bottom_view.setIcon(icon9)
        self.action_right_view = QAction(MainWindow)
        self.action_right_view.setObjectName(u"action_right_view")
        icon10 = QIcon()
        icon10.addFile(u":/icons/views/right.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_right_view.setIcon(icon10)
        self.action_left_view = QAction(MainWindow)
        self.action_left_view.setObjectName(u"action_left_view")
        icon11 = QIcon()
        icon11.addFile(u":/icons/views/left.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_left_view.setIcon(icon11)
        self.action_front_view = QAction(MainWindow)
        self.action_front_view.setObjectName(u"action_front_view")
        icon12 = QIcon()
        icon12.addFile(u":/icons/views/front.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_front_view.setIcon(icon12)
        self.action_back_view = QAction(MainWindow)
        self.action_back_view.setObjectName(u"action_back_view")
        icon13 = QIcon()
        icon13.addFile(u":/icons/views/back.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_back_view.setIcon(icon13)
        self.action_isometric_view = QAction(MainWindow)
        self.action_isometric_view.setObjectName(u"action_isometric_view")
        icon14 = QIcon()
        icon14.addFile(u":/icons/views/orthogonal.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_isometric_view.setIcon(icon14)
        self.action_node_view = QAction(MainWindow)
        self.action_node_view.setObjectName(u"action_node_view")
        self.action_node_view.setCheckable(True)
        self.action_node_view.setChecked(True)
        icon15 = QIcon()
        icon15.addFile(u":/icons/visibility/nodes.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_node_view.setIcon(icon15)
        self.action_line_view = QAction(MainWindow)
        self.action_line_view.setObjectName(u"action_line_view")
        self.action_line_view.setCheckable(True)
        self.action_line_view.setChecked(True)
        icon16 = QIcon()
        icon16.addFile(u":/icons/visibility/lines.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_line_view.setIcon(icon16)
        self.action_face_view = QAction(MainWindow)
        self.action_face_view.setObjectName(u"action_face_view")
        self.action_face_view.setCheckable(True)
        self.action_face_view.setChecked(True)
        icon17 = QIcon()
        icon17.addFile(u":/icons/visibility/faces.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_face_view.setIcon(icon17)
        self.section_plane_show_action = QAction(MainWindow)
        self.section_plane_show_action.setObjectName(u"section_plane_show_action")
        icon18 = QIcon()
        icon18.addFile(u":/icons/visibility/section_plane_view.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.section_plane_show_action.setIcon(icon18)
        self.action_hide_show_symbols = QAction(MainWindow)
        self.action_hide_show_symbols.setObjectName(u"action_hide_show_symbols")
        self.action_hide_show_symbols.setCheckable(True)
        self.action_hide_show_symbols.setChecked(True)
        icon19 = QIcon()
        icon19.addFile(u":/icons/visibility/show_symbols.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_hide_show_symbols.setIcon(icon19)
        self.action_zoom_to_fit = QAction(MainWindow)
        self.action_zoom_to_fit.setObjectName(u"action_zoom_to_fit")
        icon20 = QIcon()
        icon20.addFile(u":/icons/views/zoom_icon.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_zoom_to_fit.setIcon(icon20)
        self.action_structural_workspace = QAction(MainWindow)
        self.action_structural_workspace.setObjectName(u"action_structural_workspace")
        self.action_acoustic_workspace = QAction(MainWindow)
        self.action_acoustic_workspace.setObjectName(u"action_acoustic_workspace")
        self.action_coupled_workspace = QAction(MainWindow)
        self.action_coupled_workspace.setObjectName(u"action_coupled_workspace")
        self.action_hide_selection = QAction(MainWindow)
        self.action_hide_selection.setObjectName(u"action_hide_selection")
        icon21 = QIcon()
        icon21.addFile(u":/icons/visibility/hide_icon.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_hide_selection.setIcon(icon21)
        self.action_unhide_all = QAction(MainWindow)
        self.action_unhide_all.setObjectName(u"action_unhide_all")
        icon22 = QIcon()
        icon22.addFile(u":/icons/visibility/unhide_all_icon.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_unhide_all.setIcon(icon22)
        self.action_section_plane = QAction(MainWindow)
        self.action_section_plane.setObjectName(u"action_section_plane")
        self.action_section_plane.setCheckable(True)
        icon23 = QIcon()
        icon23.addFile(u":/icons/visibility/section_plane_config.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_section_plane.setIcon(icon23)
        self.action_plot_particle_velocity = QAction(MainWindow)
        self.action_plot_particle_velocity.setObjectName(u"action_plot_particle_velocity")
        icon24 = QIcon()
        icon24.addFile(u":/icons/image-plus.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_plot_particle_velocity.setIcon(icon24)
        self.action_plot_specific_acoustic_impedance = QAction(MainWindow)
        self.action_plot_specific_acoustic_impedance.setObjectName(u"action_plot_specific_acoustic_impedance")
        self.action_plot_specific_acoustic_impedance.setIcon(icon24)
        self.action_export_element_transfer_data = QAction(MainWindow)
        self.action_export_element_transfer_data.setObjectName(u"action_export_element_transfer_data")
        self.action_export_element_transfer_data.setIcon(icon6)
        self.action_generate_mesh = QAction(MainWindow)
        self.action_generate_mesh.setObjectName(u"action_generate_mesh")
        self.action_generate_mesh.setIcon(icon)
        self.action_theme = QAction(MainWindow)
        self.action_theme.setObjectName(u"action_theme")
        icon25 = QIcon()
        icon25.addFile(u":/icons/sun_icon.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_theme.setIcon(icon25)
        self.action_model_workspace = QAction(MainWindow)
        self.action_model_workspace.setObjectName(u"action_model_workspace")
        self.action_model_workspace.setCheckable(True)
        icon26 = QIcon()
        icon26.addFile(u":/icons/model.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_model_workspace.setIcon(icon26)
        self.action_mesh_workspace = QAction(MainWindow)
        self.action_mesh_workspace.setObjectName(u"action_mesh_workspace")
        self.action_mesh_workspace.setCheckable(True)
        self.action_mesh_workspace.setEnabled(True)
        icon27 = QIcon()
        icon27.addFile(u":/icons/mesh.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_mesh_workspace.setIcon(icon27)
        self.action_results_workspace = QAction(MainWindow)
        self.action_results_workspace.setObjectName(u"action_results_workspace")
        self.action_results_workspace.setCheckable(True)
        self.action_results_workspace.setEnabled(False)
        icon28 = QIcon()
        icon28.addFile(u":/icons/results.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_results_workspace.setIcon(icon28)
        self.action_user_preferences = QAction(MainWindow)
        self.action_user_preferences.setObjectName(u"action_user_preferences")
        icon29 = QIcon()
        icon29.addFile(u":/icons/user_preferences_icon.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_user_preferences.setIcon(icon29)
        self.action_show_materials = QAction(MainWindow)
        self.action_show_materials.setObjectName(u"action_show_materials")
        self.action_show_fluids = QAction(MainWindow)
        self.action_show_fluids.setObjectName(u"action_show_fluids")
        self.action_show_empty = QAction(MainWindow)
        self.action_show_empty.setObjectName(u"action_show_empty")
        self.action_show_empty.setCheckable(True)
        self.action_import_geometry = QAction(MainWindow)
        self.action_import_geometry.setObjectName(u"action_import_geometry")
        icon30 = QIcon()
        icon30.addFile(u":/icons/import_geometry.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_import_geometry.setIcon(icon30)
        self.action_home_exit = QAction(MainWindow)
        self.action_home_exit.setObjectName(u"action_home_exit")
        icon31 = QIcon()
        icon31.addFile(u":/icons/home.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_home_exit.setIcon(icon31)
        self.action_import_mesh = QAction(MainWindow)
        self.action_import_mesh.setObjectName(u"action_import_mesh")
        icon32 = QIcon()
        icon32.addFile(u":/icons/import_mesh.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_import_mesh.setIcon(icon32)
        self.action_ghost_view = QAction(MainWindow)
        self.action_ghost_view.setObjectName(u"action_ghost_view")
        self.action_ghost_view.setCheckable(True)
        icon33 = QIcon()
        icon33.addFile(u":/icons/visibility/ghost.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_ghost_view.setIcon(icon33)
        self.action_ghost_view.setMenuRole(QAction.MenuRole.NoRole)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.splitter = QSplitter(self.centralwidget)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setLineWidth(1)
        self.splitter.setOrientation(Qt.Orientation.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(3)
        self.stacked_setup = QStackedWidget(self.splitter)
        self.stacked_setup.setObjectName(u"stacked_setup")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stacked_setup.sizePolicy().hasHeightForWidth())
        self.stacked_setup.setSizePolicy(sizePolicy)
        self.stacked_setup.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)
        self.stacked_setup.setStyleSheet(u"")
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.page_3.setAutoFillBackground(False)
        self.page_3.setStyleSheet(u"background: red;")
        self.stacked_setup.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.page_4.setStyleSheet(u"background: blue;")
        self.stacked_setup.addWidget(self.page_4)
        self.splitter.addWidget(self.stacked_setup)
        self.render_widgets_stack = QStackedWidget(self.splitter)
        self.render_widgets_stack.setObjectName(u"render_widgets_stack")
        sizePolicy.setHeightForWidth(self.render_widgets_stack.sizePolicy().hasHeightForWidth())
        self.render_widgets_stack.setSizePolicy(sizePolicy)
        self.page_7 = QWidget()
        self.page_7.setObjectName(u"page_7")
        self.page_7.setStyleSheet(u"background: red;")
        self.render_widgets_stack.addWidget(self.page_7)
        self.page_8 = QWidget()
        self.page_8.setObjectName(u"page_8")
        self.page_8.setStyleSheet(u"background: black;")
        self.render_widgets_stack.addWidget(self.page_8)
        self.splitter.addWidget(self.render_widgets_stack)

        self.horizontalLayout.addWidget(self.splitter)

        MainWindow.setCentralWidget(self.centralwidget)
        self.status_bar = QStatusBar(MainWindow)
        self.status_bar.setObjectName(u"status_bar")
        MainWindow.setStatusBar(self.status_bar)
        self.renderer_toolbar = QToolBar(MainWindow)
        self.renderer_toolbar.setObjectName(u"renderer_toolbar")
        self.renderer_toolbar.setStyleSheet(u"\n"
"            QToolBar {\n"
"                border-style: solid;\n"
"                border-width: 1px;\n"
"                border-color: #888888;\n"
"            }")
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.renderer_toolbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1055, 25))
        self.menu_project = QMenu(self.menubar)
        self.menu_project.setObjectName(u"menu_project")
        self.menu_settings = QMenu(self.menubar)
        self.menu_settings.setObjectName(u"menu_settings")
        self.menu_view_mode = QMenu(self.menubar)
        self.menu_view_mode.setObjectName(u"menu_view_mode")
        self.menu_help = QMenu(self.menubar)
        self.menu_help.setObjectName(u"menu_help")
        self.advanced_results_menu = QMenu(self.menubar)
        self.advanced_results_menu.setObjectName(u"advanced_results_menu")
        MainWindow.setMenuBar(self.menubar)

        self.renderer_toolbar.addSeparator()
        self.renderer_toolbar.addAction(self.action_new_project)
        self.renderer_toolbar.addAction(self.action_open_project)
        self.renderer_toolbar.addAction(self.action_import_geometry)
        self.renderer_toolbar.addAction(self.action_import_mesh)
        self.renderer_toolbar.addAction(self.action_save)
        self.renderer_toolbar.addAction(self.action_save_as)
        self.renderer_toolbar.addSeparator()
        self.renderer_toolbar.addAction(self.action_top_view)
        self.renderer_toolbar.addAction(self.action_bottom_view)
        self.renderer_toolbar.addAction(self.action_right_view)
        self.renderer_toolbar.addAction(self.action_left_view)
        self.renderer_toolbar.addAction(self.action_front_view)
        self.renderer_toolbar.addAction(self.action_back_view)
        self.renderer_toolbar.addAction(self.action_isometric_view)
        self.renderer_toolbar.addAction(self.action_zoom_to_fit)
        self.renderer_toolbar.addSeparator()
        self.renderer_toolbar.addAction(self.action_node_view)
        self.renderer_toolbar.addAction(self.action_line_view)
        self.renderer_toolbar.addAction(self.action_face_view)
        self.renderer_toolbar.addAction(self.action_hide_show_symbols)
        self.renderer_toolbar.addAction(self.action_ghost_view)
        self.renderer_toolbar.addSeparator()
        self.renderer_toolbar.addAction(self.action_section_plane)
        self.renderer_toolbar.addSeparator()
        self.renderer_toolbar.addAction(self.action_hide_selection)
        self.renderer_toolbar.addAction(self.action_unhide_all)
        self.renderer_toolbar.addSeparator()
        self.renderer_toolbar.addAction(self.action_model_workspace)
        self.renderer_toolbar.addAction(self.action_mesh_workspace)
        self.renderer_toolbar.addAction(self.action_results_workspace)
        self.menubar.addAction(self.menu_project.menuAction())
        self.menubar.addAction(self.menu_settings.menuAction())
        self.menubar.addAction(self.menu_view_mode.menuAction())
        self.menubar.addAction(self.advanced_results_menu.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())
        self.menu_project.addAction(self.action_new_project)
        self.menu_project.addAction(self.action_open_project)
        self.menu_project.addAction(self.action_import_geometry)
        self.menu_project.addAction(self.action_import_mesh)
        self.menu_project.addAction(self.action_save)
        self.menu_project.addAction(self.action_save_as)
        self.menu_project.addAction(self.action_export_mesh)
        self.menu_project.addAction(self.action_capture_image)
        self.menu_project.addSeparator()
        self.menu_project.addAction(self.action_home_exit)
        self.menu_project.addAction(self.action_exit)
        self.menu_settings.addAction(self.action_theme)
        self.menu_settings.addSeparator()
        self.menu_settings.addSeparator()
        self.menu_settings.addAction(self.action_user_preferences)
        self.menu_view_mode.addAction(self.action_node_view)
        self.menu_view_mode.addAction(self.action_line_view)
        self.menu_view_mode.addAction(self.action_face_view)
        self.menu_view_mode.addSeparator()
        self.menu_view_mode.addAction(self.action_show_empty)
        self.menu_help.addAction(self.action_about_vibra)
        self.advanced_results_menu.addAction(self.action_export_element_transfer_data)

        self.retranslateUi(MainWindow)

        self.stacked_setup.setCurrentIndex(0)
        self.render_widgets_stack.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.action_new_project.setText(QCoreApplication.translate("MainWindow", u"New project", None))
        self.action_open_project.setText(QCoreApplication.translate("MainWindow", u"Open Project", None))
        self.action_recent.setText(QCoreApplication.translate("MainWindow", u"Recent", None))
        self.action_save.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(shortcut)
        self.action_save.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.action_save_as.setText(QCoreApplication.translate("MainWindow", u"Save as", None))
        self.action_export_mesh.setText(QCoreApplication.translate("MainWindow", u"Export mesh", None))
        self.action_capture_image.setText(QCoreApplication.translate("MainWindow", u"Capture Image", None))
        self.action_exit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.action_show_menu_items.setText(QCoreApplication.translate("MainWindow", u"Hide menu items", None))
        self.action_set_fluid.setText(QCoreApplication.translate("MainWindow", u"Set fluid", None))
        self.action_set_material.setText(QCoreApplication.translate("MainWindow", u"Set material", None))
        self.action_mesher_setup.setText(QCoreApplication.translate("MainWindow", u"Mesher setup", None))
        self.action_about_vibra.setText(QCoreApplication.translate("MainWindow", u"About Vibra", None))
        self.action_reset_project.setText(QCoreApplication.translate("MainWindow", u"Reset Project", None))
        self.action_top_view.setText(QCoreApplication.translate("MainWindow", u"Top View", None))
        self.action_bottom_view.setText(QCoreApplication.translate("MainWindow", u"Bottom View", None))
#if QT_CONFIG(shortcut)
        self.action_bottom_view.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+2", None))
#endif // QT_CONFIG(shortcut)
        self.action_right_view.setText(QCoreApplication.translate("MainWindow", u"Right View", None))
#if QT_CONFIG(shortcut)
        self.action_right_view.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+3", None))
#endif // QT_CONFIG(shortcut)
        self.action_left_view.setText(QCoreApplication.translate("MainWindow", u"Left View", None))
#if QT_CONFIG(shortcut)
        self.action_left_view.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+4", None))
#endif // QT_CONFIG(shortcut)
        self.action_front_view.setText(QCoreApplication.translate("MainWindow", u"Front View", None))
#if QT_CONFIG(shortcut)
        self.action_front_view.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+5", None))
#endif // QT_CONFIG(shortcut)
        self.action_back_view.setText(QCoreApplication.translate("MainWindow", u"Back View", None))
#if QT_CONFIG(shortcut)
        self.action_back_view.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+6", None))
#endif // QT_CONFIG(shortcut)
        self.action_isometric_view.setText(QCoreApplication.translate("MainWindow", u"Isometric View", None))
#if QT_CONFIG(shortcut)
        self.action_isometric_view.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+7", None))
#endif // QT_CONFIG(shortcut)
        self.action_node_view.setText(QCoreApplication.translate("MainWindow", u"Node View", None))
        self.action_line_view.setText(QCoreApplication.translate("MainWindow", u"Line View", None))
        self.action_face_view.setText(QCoreApplication.translate("MainWindow", u"Face View", None))
        self.section_plane_show_action.setText(QCoreApplication.translate("MainWindow", u"Clip Plane", None))
        self.action_hide_show_symbols.setText(QCoreApplication.translate("MainWindow", u"Symbols", None))
        self.action_zoom_to_fit.setText(QCoreApplication.translate("MainWindow", u"Zoom To Fit", None))
        self.action_structural_workspace.setText(QCoreApplication.translate("MainWindow", u"Structural Workspace", None))
        self.action_acoustic_workspace.setText(QCoreApplication.translate("MainWindow", u"Acoustic Workspace", None))
        self.action_coupled_workspace.setText(QCoreApplication.translate("MainWindow", u"Coupled Workspace", None))
        self.action_hide_selection.setText(QCoreApplication.translate("MainWindow", u"Hide Selection", None))
#if QT_CONFIG(shortcut)
        self.action_hide_selection.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+H", None))
#endif // QT_CONFIG(shortcut)
        self.action_unhide_all.setText(QCoreApplication.translate("MainWindow", u"Unhide Selection", None))
#if QT_CONFIG(shortcut)
        self.action_unhide_all.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+U", None))
#endif // QT_CONFIG(shortcut)
        self.action_section_plane.setText(QCoreApplication.translate("MainWindow", u"Configure Section Plane", None))
        self.action_plot_particle_velocity.setText(QCoreApplication.translate("MainWindow", u"Plot particle velocity", None))
        self.action_plot_specific_acoustic_impedance.setText(QCoreApplication.translate("MainWindow", u"Plot specific acoustic impedance", None))
        self.action_export_element_transfer_data.setText(QCoreApplication.translate("MainWindow", u"Export element transfer data", None))
        self.action_generate_mesh.setText(QCoreApplication.translate("MainWindow", u"Generate Mesh", None))
        self.action_theme.setText(QCoreApplication.translate("MainWindow", u"Theme", None))
        self.action_model_workspace.setText(QCoreApplication.translate("MainWindow", u"Model Workspace", None))
        self.action_mesh_workspace.setText(QCoreApplication.translate("MainWindow", u"Mesh Workspace", None))
        self.action_results_workspace.setText(QCoreApplication.translate("MainWindow", u"Results Workspace", None))
        self.action_user_preferences.setText(QCoreApplication.translate("MainWindow", u"User Preferences", None))
        self.action_show_materials.setText(QCoreApplication.translate("MainWindow", u"Show Materials", None))
        self.action_show_fluids.setText(QCoreApplication.translate("MainWindow", u"Show Fluids", None))
        self.action_show_empty.setText(QCoreApplication.translate("MainWindow", u"Show Empty", None))
        self.action_import_geometry.setText(QCoreApplication.translate("MainWindow", u"Import geometry", None))
        self.action_home_exit.setText(QCoreApplication.translate("MainWindow", u"Home Exit", None))
        self.action_import_mesh.setText(QCoreApplication.translate("MainWindow", u"Import mesh", None))
        self.action_ghost_view.setText(QCoreApplication.translate("MainWindow", u"Ghost", None))
        self.renderer_toolbar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
        self.menu_project.setTitle(QCoreApplication.translate("MainWindow", u"Project", None))
        self.menu_settings.setTitle(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.menu_view_mode.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menu_help.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.advanced_results_menu.setTitle(QCoreApplication.translate("MainWindow", u"Advanced Results", None))
    # retranslateUi



class MainWindow_UI(QMainWindow, Ui_MainWindow):
    """
    Component Hierarchy:
    - MainWindow: QMainWindow
        - centralwidget: QWidget
            - (Layout): QHBoxLayout
                    - splitter: QSplitter
                        - stacked_setup: QStackedWidget
                            - page_3: QWidget
                            - page_4: QWidget
                        - render_widgets_stack: QStackedWidget
                            - page_7: QWidget
                            - page_8: QWidget
        - status_bar: QStatusBar
        - renderer_toolbar: QToolBar
        - menubar: QMenuBar
            - menu_project: QMenu
            - menu_settings: QMenu
            - menu_view_mode: QMenu
            - menu_help: QMenu
            - advanced_results_menu: QMenu
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setupUi(self)
