# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plots/acoustic/plot_specific_acoustic_impedance_input.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(400, 240)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(400, 240))
        Dialog.setMaximumSize(QtCore.QSize(400, 240))
        Dialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Dialog.setWhatsThis("")
        self.gridLayout_4 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_4.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_4.setSpacing(4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setMinimumSize(QtCore.QSize(0, 48))
        self.frame.setMaximumSize(QtCore.QSize(520, 48))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(452, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(520, 460))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setContentsMargins(4, 4, 4, 4)
        self.gridLayout_3.setSpacing(4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 52))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 52))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setMinimumSize(QtCore.QSize(110, 30))
        self.label_10.setMaximumSize(QtCore.QSize(110, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 1, 1, 1)
        self.lineEdit_selection_id = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_selection_id.setMinimumSize(QtCore.QSize(110, 30))
        self.lineEdit_selection_id.setMaximumSize(QtCore.QSize(110, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_selection_id.setFont(font)
        self.lineEdit_selection_id.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(255,255,255)")
        self.lineEdit_selection_id.setText("")
        self.lineEdit_selection_id.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_selection_id.setObjectName("lineEdit_selection_id")
        self.gridLayout.addWidget(self.lineEdit_selection_id, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.pushButton_export_data = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_export_data.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton_export_data.setMaximumSize(QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_export_data.setFont(font)
        self.pushButton_export_data.setStyleSheet("")
        self.pushButton_export_data.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/save_as.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_export_data.setIcon(icon)
        self.pushButton_export_data.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_export_data.setFlat(False)
        self.pushButton_export_data.setObjectName("pushButton_export_data")
        self.gridLayout.addWidget(self.pushButton_export_data, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        self.gridLayout_3.addWidget(self.frame_4, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 52))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 52))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_47 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_47.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_47.setSpacing(2)
        self.gridLayout_47.setObjectName("gridLayout_47")
        self.pushButton_plot_data = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_plot_data.setMinimumSize(QtCore.QSize(120, 32))
        self.pushButton_plot_data.setMaximumSize(QtCore.QSize(120, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_plot_data.setFont(font)
        self.pushButton_plot_data.setStyleSheet("")
        self.pushButton_plot_data.setFlat(False)
        self.pushButton_plot_data.setObjectName("pushButton_plot_data")
        self.gridLayout_47.addWidget(self.pushButton_plot_data, 0, 1, 1, 1)
        self.pushButton_exit = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_exit.setMinimumSize(QtCore.QSize(120, 32))
        self.pushButton_exit.setMaximumSize(QtCore.QSize(120, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setStyleSheet("")
        self.pushButton_exit.setFlat(False)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.gridLayout_47.addWidget(self.pushButton_exit, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_3, 2, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_6.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_6.setHorizontalSpacing(6)
        self.gridLayout_6.setVerticalSpacing(2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setMinimumSize(QtCore.QSize(110, 30))
        self.label_2.setMaximumSize(QtCore.QSize(110, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 1, 1, 1)
        self.comboBox_selector_filter = QtWidgets.QComboBox(self.frame_5)
        self.comboBox_selector_filter.setMinimumSize(QtCore.QSize(110, 30))
        self.comboBox_selector_filter.setMaximumSize(QtCore.QSize(110, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_selector_filter.setFont(font)
        self.comboBox_selector_filter.setStyleSheet("")
        self.comboBox_selector_filter.setObjectName("comboBox_selector_filter")
        self.comboBox_selector_filter.addItem("")
        self.comboBox_selector_filter.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_selector_filter, 0, 2, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setMinimumSize(QtCore.QSize(40, 30))
        self.frame_6.setMaximumSize(QtCore.QSize(40, 30))
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_6.addWidget(self.frame_6, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 0, 4, 1, 1)
        self.gridLayout_3.addWidget(self.frame_5, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.comboBox_selector_filter.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Plot frequency response"))
        self.label.setText(_translate("Dialog", "Plot the specific acoustic impedance"))
        self.label_10.setText(_translate("Dialog", "Selected ID: "))
        self.pushButton_export_data.setToolTip(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:400;\">Press to export the current response function</span></p></body></html>"))
        self.pushButton_plot_data.setText(_translate("Dialog", "  Plot data"))
        self.pushButton_exit.setText(_translate("Dialog", "Exit"))
        self.label_2.setText(_translate("Dialog", "Selector filter: "))
        self.comboBox_selector_filter.setItemText(0, _translate("Dialog", "   Surfaces"))
        self.comboBox_selector_filter.setItemText(1, _translate("Dialog", "   Nodes"))


class PlotSpecificAcousticImpedanceInput_UI(QtWidgets.QDialog, Ui_Dialog):
    """
    Component Hierarchy:
    - Dialog: QDialog
        - (Layout): QGridLayout
                - frame: QFrame
                    - (Layout): QGridLayout
                            - label: QLabel
                - frame_2: QFrame
                    - (Layout): QGridLayout
                            - frame_4: QFrame
                                - (Layout): QGridLayout
                                        - label_10: QLabel
                                        - lineEdit_selection_id: QLineEdit
                                        - pushButton_export_data: QPushButton
                            - frame_3: QFrame
                                - (Layout): QGridLayout
                                        - pushButton_plot_data: QPushButton
                                        - pushButton_exit: QPushButton
                            - frame_5: QFrame
                                - (Layout): QGridLayout
                                        - label_2: QLabel
                                        - comboBox_selector_filter: QComboBox
                                        - frame_6: QFrame
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setupUi(self)
